services:
    database:
        image: postgres:16.2-alpine3.19
        container_name: "simple-pass-database"
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${DATABASE_USERNAME}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
        volumes:
            - 'db:/var/lib/postgresql/data'

volumes:
    db:
